services:
  app:
    build:
      context: ./backend
      args:
        APP_KEY: "base64:lRtqEa9h1aAPN72o95qaSg===="
    container_name: gestion-consultas-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_NAME=GestionConsultas
      - APP_ENV=local
      - APP_KEY=base64:lRtqEa9h1aAPN72o95qaSg====
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gestion_consulta_dietetica
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_CIPHER=aes-128-cbc
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./frontend
    container_name: gestion-consultas-frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - app
    networks:
      - app-network

  db:
    build: .
    container_name: gestion-consultas-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gestion_consulta_dietetica
      - MYSQL_ROOT_HOST=%
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gestion-consultas-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: